root = "."
tmp_dir = "tmp"

[build]
cmd = "make tmp/main"
# Binary file yields from `cmd`.
bin = "tmp/main"
# Customize binary.
full_bin = "make serve"
# Watch these filename extensions.
include_ext = [
    "go",
    "html",
    "json",
    "tmpl",
    "tpl",
]
# Ignore these filename extensions or directories.
exclude_dir = [
    "dialogues",
    "gfx",
    "node_modules",
    "public",
    "screenshots",
    "styles",
]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 300 # ms
# Stop running old binary when build errors occur.
stop_on_error = true

[log]
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
